name: Publish Playwright Test Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 17 * * 1-5'

jobs:
  ui_test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npm run test

      - name: Copy Contents of Playwright Report
        if: always()
        run: |
          mkdir -p ${{ github.workspace }}/generated-report
          cp -r ${{ github.workspace }}/playwright-report/* ${{ github.workspace }}/generated-report/

      - name: Configure SSH Key
        if: always()
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remove Old Host Key
        if: always()
        run: ssh-keygen -R github.com || true

      - name: Ensure Known Hosts
        if: always()
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Target Repository
        if: always()
        run: |
          git clone git@github.com:sabbir-of/playwright-report.git gh-pages-repo
          cd gh-pages-repo
          git remote set-url origin git@github.com:sabbir-of/playwright-report.git
          git checkout -B gh-pages

      - name: Clean Up Existing Files
        if: always()
        run: |
          cd gh-pages-repo
          git rm -rf . || true

      - name: Configure Git User and Handle Line Endings
        if: always()
        working-directory: gh-pages-repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "sabbir.of@gmail.com"
          git config core.autocrlf true

      - name: Copy New Report
        if: always()
        run: |
          cp -r ${{ github.workspace }}/generated-report/* gh-pages-repo/

      - name: Commit and Push Changes
        if: always()
        working-directory: gh-pages-repo
        run: |
          git add .
          git commit -m "Update Playwright report" || echo "No changes to commit"
          git push -u origin gh-pages --force
